config/routes.rb
Aiki3::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :entrances

  resources :katas

  resources :styles

  resources :senseis

  resources :videos do
    get 'needs_review', on: :collection
  end

  resources :ranks

  resources :aiki_formats

  resources :wazas do
    get 'master_grid', on: :collection
    get 'show_master_grid', on: :collection
    get 'only_on_test', on: :collection
    get 'display'
    get 'remote_display'
    get 'remote_waza'
    get 'rows', on: :collection
  end

  resources :levels

  resources :swords

  resources :kaitens

  resources :directions

  resources :techniques

  resources :maka_komis

  resources :hand_applied_tos

  resources :attack_heights

  resources :attacks

  resources :stances

  root 'wazas#only_on_test'

end

app/models/waza.rb
class Waza < ActiveRecord::Base
  include Printable
  include Searchable
  include SeedFuSerializeable

  before_save :set_waza_name

  belongs_to :stance, inverse_of: :wazas
  accepts_nested_attributes_for :stance

  belongs_to :entrance, inverse_of: :wazas
  accepts_nested_attributes_for :entrance

  belongs_to :attack, inverse_of: :wazas
  accepts_nested_attributes_for :attack

  belongs_to :attack_height, inverse_of: :wazas
  accepts_nested_attributes_for :attack_height

  belongs_to :hand_applied_to, inverse_of: :wazas
  accepts_nested_attributes_for :hand_applied_to

  belongs_to :maka_komi, inverse_of: :wazas
  accepts_nested_attributes_for :maka_komi

  belongs_to :technique, inverse_of: :wazas
  accepts_nested_attributes_for :technique

  belongs_to :direction, inverse_of: :wazas
  accepts_nested_attributes_for :direction

  belongs_to :kaiten, inverse_of: :wazas
  accepts_nested_attributes_for :kaiten

  belongs_to :sword, inverse_of: :wazas
  accepts_nested_attributes_for :sword

  belongs_to :level, inverse_of: :wazas
  accepts_nested_attributes_for :level

  has_many :videos
  has_many :aiki_formats, through: :videos
  has_many :ranks, through: :videos

  scope :for_stance, ->(stance) { where(stance: stance) }
  scope :for_entrance, ->(entrance) { where(entrance: entrance) }
  scope :for_attack, ->(attack) { where(attack: attack) }
  scope :for_attack_height, ->(attack_height) { where(attack_height: attack_height) }
  scope :for_hand_applied_to, ->(hand_applied_to) { where(hand_applied_to: hand_applied_to) }
  scope :for_maka_komi, ->(maka_komi) { where(maka_komi: maka_komi) }
  scope :for_technique, ->(technique) { where(technique: technique) }
  scope :for_direction, ->(direction) { where(direction: direction) }
  scope :for_kaiten, ->(kaiten) { where(kaiten: kaiten) }
  scope :for_sword, ->(sword) { where(sword: sword) }
  scope :for_level, ->(level) { where(level: level) }
  scope :on_test, -> { joins(:videos).merge(Video.on_test) }

  validates :technique, presence: true

  # def to_h
  #   attributes.select{|k,_| !%w(id created_at updated_at name).include?(k)}
  # end

  def self.wazas_hash(wazas)
    h = {}
    wazas.each do |waza|
      name, whash = waza.waza_hash
      h[name] = whash
    end
    h
  end

  def self.master_hash(options={})
    master = Hash.new
    duplicates = Hash.new

    user = options.fetch(:user) { nil }

    if options[:search].present?
      wazas = Video.wazas(Video.search(options[:search])) rescue []
    else
      wazas = Waza.all
      if options[:only_on_test]
        wazas = wazas.on_test
      end
    end

    wazas = wazas.to_a rescue []

    wazas.compact.sort_by{ |w| [w.name, w.id] }.each do |waza|
      next unless waza.videos.has_aiki_format.any?
      next unless include_based_on?(waza, options)
      next if options[:format].present? && !include_format?(waza.aiki_formats.map(&:name), options)
      next if options[:rank].present? && !include_rank?(waza.ranks.map(&:name), options)

      waza_name = waza.name
      includes = []
      unless waza_name.include? waza.stance.to_s
        includes << waza.stance.to_s
      end
      unless waza_name.include? waza.attack.to_s
        includes << waza.attack.to_s
      end
      unless waza_name.include? waza.technique.to_s
        includes << waza.technique.to_s
      end
      if includes.any?
        waza_name += " (#{includes.join(', ')})"
      end

      master[waza] ||= Hash.new

      master[waza][:name] = waza_name
      waza.videos.each do |video|
        next if video.needs_review? && !user.has_role?(:superuser)
        next if options[:format] && options[:format] != video.format
        next if options[:rank] && options[:rank] != video.rank.name
        next if options[:stance] && options[:stance] != video.stance.name
        next if options[:attack] && options[:attack] != video.attack.name
        next if options[:technique] && options[:technique] != video.technique.name
        next if options[:only_on_test] && !video.on_test?
        master[waza][:videos] ||= Hash.new
        master[waza][:videos][video.format] ||= Array.new
        unless master[waza][:videos][video.format].include? video
          master[waza][:videos][video.format] << video
        end
      end

      if master[waza][:videos].nil? || master[waza][:videos].empty?
        master.delete(waza)
      else
        if options[:search].present?
          master[waza][:sub_name] = waza.technical_name
        else
          if duplicates[waza_name]
            master[waza][:sub_name] = waza.technical_name
            unless master[duplicates[waza_name]][:sub_name].present?
              master[duplicates[waza_name]][:sub_name] = duplicates[waza_name].technical_name
            end
          else
            duplicates[waza_name] = waza
          end
        end
      end

    end

    master
  end

  def self.include_format?(formats, options)
    return true unless options[:format].present? && formats.any?
    formats.include? options[:format]
  end

  def self.include_rank?(ranks, options)
    return true unless options[:rank].present? && ranks.any?
    ranks.include? options[:rank]
  end

  def self.include_based_on?(waza, options)
    return true if options.empty?

    technique_include = options[:technique].present? ? false : true
    if options[:technique].present? && waza.technique
      technique_include = options[:technique] == waza.technique.name
    end

    stance_include = options[:stance].present? ? false : true
    if options[:stance].present? && waza.stance
      stance_include = options[:stance] == waza.stance.name
    end

    attack_include = options[:attack].present? ? false : true
    if options[:attack].present? && waza.attack
      attack_include = options[:attack] == waza.attack.name
    end

    return technique_include && stance_include && attack_include
  end

  def formats
    aiki_formats
  end

  def technical_name
    @tech_name ||= [stance,
                    entrance,
                    attack,
                    attack_height,
                    hand_applied_to,
                    maka_komi,
                    technique,
                    direction,
                    kaiten,
                    sword,
                    level].map{|a| a.name rescue nil}.compact.join(' ')
  end

  def short_name
    parts = [stance]
    parts << attack if attack && attack.name != 'Katatedori'
    parts << technique
    parts << direction

    @short_tech_name ||= parts.map{|a| a.name rescue nil}.compact.join(' ')
  end

  def inspect
    "<#{identify(:id, :technique)}(#{name})>"
  end

  def waza_hash
    h = {
      waza: self,
      formats: {}
    }

    videos.each do |v|
      h[:formats][v.format] ||= []
      h[:formats][v.format] << v
    end

    [name, h]
  end

  def set_waza_name
    do_set_waza_name unless name.present?
  end

  def do_set_waza_name
    self.name = short_name
  end
end

app/controllers/wazas_controller.rb
class WazasController < ApplicationController
  before_action :signed_in_user
  before_action :set_waza, only: [:show, :edit, :update, :destroy]

  def rows
  end

  def display
    @stance = Stance.find_by(id: params[:stance]) rescue nil if params[:stance]
    @attack = Attack.find_by(id: params[:attack]) rescue nil if params[:attack]
    @technique = Technique.find_by(id: params[:technique]) rescue nil if params[:technique]
    @format = AikiFormat.find_by(id: params[:format]) rescue nil if params[:format]
    @rank = Rank.find_by(id: params[:rank]) rescue nil if params[:rank]
    if params[:waza_id]
      @waza = Waza.find_by(id: params[:waza_id]) rescue nil
    end
    @waza = Video.first.waza unless @waza
    @video = Video.find_by(id: params[:video_id]) rescue nil if params[:video_id]
    @search = params[:search]
    @include_waza_form = true
  end

  def remote_display
    @waza = Waza.find_by(id: params[:waza_id]) rescue nil if params[:waza_id]
    @video = Video.find_by(id: params[:video_id]) rescue nil if params[:video_id]
    @include_waza_form = true
    if @waza && @video && @video.waza.id != @waza.id
      @video = nil
      @include_waza_form = false
    end
  end

  def remote_waza
    @waza = Waza.find_by(id: params.fetch(:waza_id, 0)) || Waza.new
  end

  def show_master_grid
    @master_hash = {}
    render :master_grid
  end

  def only_on_test
    redirect_to master_grid_wazas_path(only_on_test: 1)
  end

  def master_grid
    options = { user: current_user }
    if params[:stance].present?
      @stance = Stance.find_by(id: params[:stance]) rescue nil
      if @stance
        options[:stance] = @stance.name
        @stance = @stance.id
      end
    end

    if params[:attack].present?
      @attack = Attack.find_by(id: params[:attack]) rescue nil
      if @attack
        options[:attack] = @attack.name
        @attack = @attack.id
      end
    end

    if params[:technique].present?
      @technique = Technique.find_by(id: params[:technique]) rescue nil
      if @technique
        options[:technique] = @technique.name
        @technique = @technique.id
      end
    end

    if params[:format].present?
      @format = AikiFormat.find_by(id: params[:format]) rescue nil
      if @format
        options[:format] = @format.to_s
        @format = @format.id
      end
    end

    if params[:rank].present?
      @rank = Rank.find_by(id: params[:rank]) rescue nil
      if @rank
        options[:rank] = @rank.to_s
        @rank = @rank.id
      end
    end

    if params[:search].present?
      @search = params[:search]
      options[:search] = params[:search]
    end

    @only_on_test = options[:only_on_test] = params.fetch("only_on_test", "0") == "1" ? true : false

    @master_hash = Waza.master_hash(options)
  end

  # GET /wazas
  # GET /wazas.json
  def index
    @wazas = Waza.all.sort_by{ |w| [w.name, w.id] }
    @count = Waza.count
    render action: "index", layout: "admin"
  end

  # GET /wazas/1
  # GET /wazas/1.json
  def show
    render action: "show", layout: "admin"
  end

  # GET /wazas/new
  def new
    @waza = Waza.new
    render action: "new", layout: "admin"
  end

  # GET /wazas/1/edit
  def edit
    render action: "edit", layout: "admin"
  end

  # POST /wazas
  # POST /wazas.json
  def create
    @waza = Waza.new(waza_params)
    respond_to do |format|
      if @waza.save
        format.html { redirect_to @waza, notice: 'Waza was successfully created.' }
        format.json { render action: 'show', status: :created, location: @waza }
      else
        format.html { render action: 'new' }
        format.json { render json: @waza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wazas/1
  # PATCH/PUT /wazas/1.json
  def update
    respond_to do |format|
      if @waza.update(waza_params)
        format.html { redirect_to @waza, notice: 'Waza was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @waza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wazas/1
  # DELETE /wazas/1.json
  def destroy
    @waza.destroy
    respond_to do |format|
      format.html { redirect_to wazas_url }
      format.json { head :no_content }
    end
  end

  private

    def set_waza
      @waza = Waza.find(params[:id]) rescue Video.first.waza
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waza_params
      params.require(:waza).permit(:name, :stance_id, :entrance_id, :attack_id, :attack_height_id, :hand_applied_to_id, :maka_komi_id, :technique_id, :direction_id, :kaiten_id, :sword_id, :level_id)
    end
end

app/helpers/wazas_helper.rb
module WazasHelper
end

app/views/wazas/_back_to_grid.html.erb
<% if @stance || @attack || @technique || @format || @rank || @search %>
  <%= link_to 'Back to Grid', master_grid_wazas_path(stance: @stance,
                                                     attack: @attack,
                                                     technique: @technique,
                                                     format: @format,
                                                     rank: @rank,
                                                     search: @search) %>
<% end %>

app/views/wazas/_display.html.erb
<div id="vid">

  <div id="waza_format">
    <%
      waza_formats = @waza.formats
      vid_format = waza_formats.first

      if !@video
        format = @format ? @format : vid_format
        @video = @waza.videos.has_aiki_format.where(aiki_format: format).order(primary: :desc).order(:rank_id).first rescue nil
      end

      if @video
        vid_format = @video.aiki_format
      end
    %>

    <%= render 'video_tab_head', waza: @waza, waza_formats: waza_formats.map(&:name), vid_format: vid_format %>

    <%= render 'video_tab_pane', waza: @waza, video: @video, vid_format: vid_format %>
  </div>

</div>

app/views/wazas/_filter_form.html.erb
<div class="row pad_top_bottom">
  <div class="col-md-12"><h4>Filters</h4></div>
</div>
<div class="row pad_top_bottom">
  <div class="col-md-3">
    <%= label_tag "stance", "Stance:" %>
  </div>
  <div class="col-md-7">
    <%= select_tag "stance", options_for_select(Stance.order(:name).map{|s| [s.name, s.id]}, @stance), include_blank: true, class: 'full_width' %>
  </div>
</div>
<div class="row pad_top_bottom">
  <div class="col-md-3">
    <%= label_tag "attack", "Attack:" %>
  </div>
  <div class="col-md-7">
    <%= select_tag "attack", options_for_select(Attack.order(:name).map{|s| [s.name, s.id]}, @attack), include_blank: true, class: 'full_width' %>
  </div>
</div>
<div class="row pad_top_bottom">
  <div class="col-md-3">
    <%= label_tag "technique", "Technique:" %>
  </div>
  <div class="col-md-7">
    <%= select_tag "technique", options_for_select(Technique.order(:name).map{|s| [s.name, s.id]}, @technique), include_blank: true, class: 'full_width' %>
  </div>
</div>
<div class="row pad_top_bottom">
  <div class="col-md-3">
    <%= label_tag "format", "Format:" %>
  </div>
  <div class="col-md-7">
    <%= select_tag "format", options_for_select(AikiFormat.all.map{|s| [s.name, s.id]}, @format), include_blank: true, class: 'full_width' %>
  </div>
</div>
<div class="row pad_top_bottom">
  <div class="col-md-3">
    <%= label_tag "rank", "Rank:" %>
  </div>
  <div class="col-md-7">
    <%= select_tag "rank", options_for_select(Rank.all.map{|s| [s.name, s.id]}, @rank), include_blank: true, class: 'full_width' %>
  </div>
</div>
<div class="row pad_top_bottom">
  <div class="col-md-3">
    <%= label_tag "on_test", "Only On Test:" %>
  </div>
  <div class="col-md-2" style="padding-left: 0px; margin-left: -5px;">
    <%= check_box_tag "only_on_test", '1', @only_on_test %>
  </div>
</div>
<div class="row pad_top_bottom">
  <div class="col-md-offset-3 col-md-7">
    <span class="pull-right">
      <% if @stance || @attack || @technique || @format || @rank || @search || @only_on_test %>
        <%= link_to 'Clear Search/Filters', show_master_grid_wazas_path , class: "btn", role: "button" %>
      <% end %>
      <%= submit_tag 'Go', class: "btn", role: "button" %>
    </span>
  </div>
</div>

app/views/wazas/_form.html.erb
  <div class="row pad_sides" style="border-bottom: 1px solid #bbb; margin: 0">&nbsp;</div>

  <%
    waza ||= waza_form.object
    hide_name ||= false
  %>

    <script type="text/javascript">
    jQuery(function($) {
      $("#waza_list").change(function() {
        var state = $('select#waza_list :selected').val();
        if(state == "") state="0";
        jQuery.getScript('/wazas/' + state + '/remote_waza')
        return false;
      });
    })
    </script>

  <div class="row pad_top_bottom">
    <div class="col-md-2">
      <h2>Waza</h2>
    </div>
    <div class="col-md-9"  style="padding-top: 25px;">
      <div class="field">
        <%= label_tag "waza_list", "Pre-Populate with:" %>
        <%= select_tag "waza_list",
      options_for_select(Waza.order(:stance_id, :attack_id, :technique_id, :direction_id).collect {|k| ["(#{k.id}) #{k.technical_name}", k.id] },
                         waza.id),
      { include_blank: true } %>
      </div>
    </div>
  </div>

  <% if waza && waza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waza.errors.count, "error") %> prohibited this waza from being saved:</h2>

      <ul>
      <% waza.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row pad_top_bottom">
    <% unless hide_name %>
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :name %><br>
        <%= waza_form.text_field :name %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="row pad_top_bottom">
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :stance_id %><br>
        <%= waza_form.select :stance_id, options_for_select(Stance.order(:name).collect { |k| [ k.name, k.id ] }, waza.stance_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= waza_form.label :entrance_id %><br>
        <%= waza_form.select :entrance_id, options_for_select(Entrance.order(:name).collect { |k| [ k.name, k.id ] }, waza.entrance_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :attack_id %><br>
        <%= waza_form.select :attack_id, options_for_select(Attack.order(:name).collect { |k| [ k.name, k.id ] }, waza.attack_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :attack_height_id %><br>
        <%= waza_form.select :attack_height_id, options_for_select(AttackHeight.order(:name).collect { |k| [ k.name, k.id ] }, waza.attack_height_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :hand_applied_to_id %><br>
        <%= waza_form.select :hand_applied_to_id, options_for_select(HandAppliedTo.order(:name).collect { |k| [ k.name, k.id ] }, waza.hand_applied_to_id), { include_blank: true } %>
      </div>
    </div>
  </div>

  <div class="row pad_top_bottom">
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :maka_komi_id %><br>
        <%= waza_form.select :maka_komi_id, options_for_select(MakaKomi.order(:name).collect { |k| [ k.name, k.id ] }, waza.maka_komi_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= waza_form.label :technique_id %><br>
        <%= waza_form.select :technique_id, options_for_select(Technique.order(:name).collect { |k| [ k.name, k.id ] }, waza.technique_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :direction_id %><br>
        <%= waza_form.select :direction_id, options_for_select(Direction.order(:name).collect { |k| [ k.name, k.id ] }, waza.direction_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :kaiten_id %><br>
        <%= waza_form.select :kaiten_id, options_for_select(Kaiten.order(:name).collect { |k| [ k.name, k.id ] }, waza.kaiten_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :sword_id %><br>
        <%= waza_form.select :sword_id, options_for_select(Sword.order(:name).collect { |k| [ k.name, k.id ] }, waza.sword_id), { include_blank: true } %>
      </div>
    </div>
  </div>

  <div class="row pad_top_bottom">
    <div class="col-md-2">
      <div class="field">
        <%= waza_form.label :level_id %><br>
        <%= waza_form.select :level_id, options_for_select(Level.all.collect { |k| [ k.name, k.id ] }, waza.level_id), { include_blank: true } %>
      </div>
    </div>
  </div>

app/views/wazas/_sensei_notes.html.erb
<p><%= video %>. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/wazas/_video.html.erb
<%
  width ||= "560"
  height ||= "315"
%>
<div class="pad_sides">
  <div class="videowrapper">
    <% if video.youtube_id %>
      <iframe id="player" class="movie" width="<%= width %>" height="<%= height %>" src="<%= @ssl ? 'https' : 'http' %>://www.youtube.com/embed/<%= video.youtube_id %>?rel=0" frameborder="1" html5="1" allowfullscreen></iframe>
    <% else %>
      <%= render 'wazas/video_not_uploaded' %>
    <% end %>
  </div>
</div>

app/views/wazas/_video_not_uploaded.html.erb
<%= image_tag 'Nishio_patch_dark.png' %>
<h2>Video Not Available</h2>

app/views/wazas/_video_tab_head.html.erb
<ul class="nav nav-tabs">
  <% 
    AikiFormat.all.each do |format|
      tab_state = 'disabled'
      tab_state = 'active' if format.id == vid_format.id
  %>
    <% if vid_format.id == format.id %>
      <li class="active"><%= link_to format, format %></li>
    <% elsif waza_formats.include?(format.to_s) %>
      <li><%= link_to format, waza_remote_display_path(waza_id: @waza.id, video_id: @waza.videos.where(aiki_format: format).first.id), remote: true %></li>
    <% else %>
      <li class="disabled"><%= link_to format, '#', class: "disabled_link" %></li>
    <% end %>
  <% end %>
</ul>

app/views/wazas/_video_tab_pane.html.erb
<div class="tab-content">
  <div class="tab-pane active" id="tab<%= video.aiki_format.id %>">
    <br/>
    <div class="row pad_sides">
      <div class="col-md-12"><label><%= video.format %>:&nbsp;</label></div>
    </div>
    <br/>

    <%= render 'video_rank_rows', waza: waza, video: video, vid_format: vid_format %>

    <div class="row">
      <div class="col-md-8">
        <%= render 'video', video: video, width: 688, height: 387 %>
      </div>
    </div>
  <% if can?(:update, :video) %>
    <div class="row pad_sides">
      <div class="col-md-12">
        <%= render 'videos/form', display: 'waza_display' %>
      </div>
    </div>
  <% end %>

  </div>
</div>

app/views/wazas/master_grid.html.erb
<div class="pad_all aiki_box" style="margin-right: 2px">
  <%= render 'grid', master_hash: @master_hash %>
</div>

app/views/wazas/new.html.erb
<h1>New waza</h1>

<%= render 'form' %>

<%= link_to 'Back', wazas_path %>

app/views/wazas/remote_waza.js.erb
<% if @waza %>
  $("#waza_form").replaceWith("<%= escape_javascript(render('videos/video_waza', waza: @waza)) %>")
<% end %>

app/views/wazas/rows.html.erb
          
          
<div class="row">
             <div class="col-lg-6">
          <div class="panel panel-default">
            <div class="panel-heading"><h3>Object Store</h3></div>
            <div class="panel-body">
<table class="table table-condensed" style="border-collapse:collapse;">

    <thead>
        <tr><th>&nbsp;</th>
            <th>Job Name</th>
            <th>Description</th>
            <th>Provider Name</th>
            <th>Region</th>
            <th>Status</th>
        </tr>
    </thead>

    <tbody>
        <tr data-toggle="collapse" data-target="#demo1" class="accordion-toggle">
                  <td><button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button></td>
            <td>OBS Name</td>
            <td>OBS Description</td>
            <td>hpcloud</td>
            <td>nova</td>
          <td> created</td>

        </tr>
        <tr>
            <td colspan="12" class="hiddenRow"><div class="accordian-body collapse" id="demo1"> 
              <table class="table table-striped">
                      <thead>
                        <tr><td><a href="WorkloadURL">Workload link</a></td><td>Bandwidth: Dandwidth Details</td><td>OBS Endpoint: end point</td></tr>
                        <tr><th>Access Key</th><th>Secret Key</th><th>Status </th><th> Created</th><th> Expires</th><th>Actions</th></tr>
                      </thead>
                      <tbody>
                        <tr><td>access-key-1</td><td>secretKey-1</td><td>Status</td><td>some date</td><td>some date</td><td><a href="#" class="btn btn-default btn-sm">
                  <i class="glyphicon glyphicon-cog"></i></a></td></tr>
                        
                     
                    
                      </tbody>
                </table>
              
              </div> </td>
        </tr>
        <tr data-toggle="collapse" data-target="#demo2" class="accordion-toggle">
                <td><button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button></td>
                <td>OBS Name</td>
            <td>OBS Description</td>
            <td>hpcloud</td>
            <td>nova</td>
          <td> created</td>
        </tr>
        <tr>
            <td colspan="6" class="hiddenRow"><div id="demo2" class="accordian-body collapse">Demo2</div></td>
        </tr>
        <tr data-toggle="collapse" data-target="#demo3" class="accordion-toggle">
            <td><button class="btn btn-default btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button></td>
            <td>OBS Name</td>
            <td>OBS Description</td>
            <td>hpcloud</td>
            <td>nova</td>
          <td> created</td>
        </tr>
        <tr>
            <td colspan="6" class="hiddenRow"><div id="demo3" class="accordian-body collapse">Demo3</div></td>
        </tr>
    </tbody>
</table>
            </div>
        
          </div> 
        
      </div>
       
</div>

app/views/wazas/show.html.erb
<h1><%= @waza.name || 'Not Set' %></h1>

<%= link_to 'Edit', edit_waza_path(@waza) %> |
<%= link_to 'Back', wazas_path %>
<br/>
<br/>

<p>
  <strong>ID:</strong>
  <%= @waza.id || 'n/a' %>
</p>

<p>
  <strong>Name:</strong>
  <%= @waza.name || 'n/a' %>
</p>

<p>
  <strong>Stance:</strong>
  <%= @waza.stance || 'n/a' %>
</p>

<p>
  <strong>Entrance:</strong>
  <%= @waza.entrance || 'n/a' %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @waza.attack || 'n/a' %>
</p>

<p>
  <strong>Attack height:</strong>
  <%= @waza.attack_height || 'n/a' %>
</p>

<p>
  <strong>Hand applied to:</strong>
  <%= @waza.hand_applied_to || 'n/a' %>
</p>

<p>
  <strong>Maka komi:</strong>
  <%= @waza.maka_komi || 'n/a' %>
</p>

<p>
  <strong>Technique:</strong>
  <%= @waza.technique || 'n/a' %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @waza.direction || 'n/a' %>
</p>

<p>
  <strong>Kaiten:</strong>
  <%= @waza.kaiten || 'n/a' %>
</p>

<p>
  <strong>Sword:</strong>
  <%= @waza.sword || 'n/a' %>
</p>

<p>
  <strong>Level:</strong>
  <%= @waza.level || 'n/a' %>
</p>

<br/>
<%= link_to 'Edit', edit_waza_path(@waza) %> |
<%= link_to 'Back', wazas_path %>

<% if @waza.videos.any? %>
  <h2>Videos</h2>
  <%= render 'videos/list', videos: @waza.videos %>
<% end %>