config/routes.rb
Aiki3::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :entrances

  resources :katas

  resources :styles

  resources :senseis

  resources :videos do
    get 'needs_review', on: :collection
  end

  resources :ranks

  resources :aiki_formats

  resources :wazas do
    get 'master_grid', on: :collection
    get 'show_master_grid', on: :collection
    get 'only_on_test', on: :collection
    get 'display'
    get 'remote_display'
    get 'remote_waza'
    get 'rows', on: :collection
  end

  resources :levels

  resources :swords

  resources :kaitens

  resources :directions

  resources :techniques

  resources :maka_komis

  resources :hand_applied_tos

  resources :attack_heights

  resources :attacks

  resources :stances

  root 'wazas#only_on_test'

end

app/models/attack_height.rb
class AttackHeight < ActiveRecord::Base
  include WazaAttribute
  include Searchable
  include SeedFuSerializeable

  has_many :wazas, inverse_of: :attack_height
  has_many :videos, through: :wazas
end

app/controllers/attack_heights_controller.rb
class AttackHeightsController < AdminController
  before_action :set_attack_height, only: [:show, :edit, :update, :destroy]

  # GET /attack_heights
  # GET /attack_heights.json
  def index
    @attack_heights = AttackHeight.all
  end

  # GET /attack_heights/1
  # GET /attack_heights/1.json
  def show
  end

  # GET /attack_heights/new
  def new
    @attack_height = AttackHeight.new
  end

  # GET /attack_heights/1/edit
  def edit
  end

  # POST /attack_heights
  # POST /attack_heights.json
  def create
    @attack_height = AttackHeight.new(attack_height_params)

    respond_to do |format|
      if @attack_height.save
        format.html { redirect_to @attack_height, notice: 'Attack height was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attack_height }
      else
        format.html { render action: 'new' }
        format.json { render json: @attack_height.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attack_heights/1
  # PATCH/PUT /attack_heights/1.json
  def update
    respond_to do |format|
      if @attack_height.update(attack_height_params)
        format.html { redirect_to @attack_height, notice: 'Attack height was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attack_height.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attack_heights/1
  # DELETE /attack_heights/1.json
  def destroy
    @attack_height.destroy
    respond_to do |format|
      format.html { redirect_to attack_heights_url }
      format.json { head :no_content }
    end
  end

  private
    
    def set_attack_height
      @attack_height = AttackHeight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attack_height_params
      params.require(:attack_height).permit(:name, :description)
    end
end

app/helpers/attack_heights_helper.rb
module AttackHeightsHelper
end

app/views/attack_heights/_form.html.erb
<%= form_for(@attack_height) do |f| %>
  <% if @attack_height.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attack_height.errors.count, "error") %> prohibited this attack_height from being saved:</h2>

      <ul>
      <% @attack_height.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attack_heights/edit.html.erb
<h1>Editing attack_height</h1>

<%= render 'form' %>

<%= link_to 'Show', @attack_height %> |
<%= link_to 'Back', attack_heights_path %>

app/views/attack_heights/index.html.erb
<h1>Listing attack_heights</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attack_heights.each do |attack_height| %>
      <tr>
        <td><%= attack_height.id %></td>
        <td><%= attack_height.name %></td>
        <td><%= attack_height.description %></td>
        <td><%= link_to 'Show', attack_height %></td>
        <td><%= link_to 'Edit', edit_attack_height_path(attack_height) %></td>
        <td><%= link_to 'Destroy', attack_height, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attack height', new_attack_height_path %>

app/views/attack_heights/new.html.erb
<h1>New attack_height</h1>

<%= render 'form' %>

<%= link_to 'Back', attack_heights_path %>

app/views/attack_heights/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @attack_height.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attack_height.description %>
</p>

<%= link_to 'Edit', edit_attack_height_path(@attack_height) %> |
<%= link_to 'Back', attack_heights_path %>