config/routes.rb
Aiki3::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :entrances

  resources :katas

  resources :styles

  resources :senseis

  resources :videos do
    get 'needs_review', on: :collection
  end

  resources :ranks

  resources :aiki_formats

  resources :wazas do
    get 'master_grid', on: :collection
    get 'show_master_grid', on: :collection
    get 'only_on_test', on: :collection
    get 'display'
    get 'remote_display'
    get 'remote_waza'
    get 'rows', on: :collection
  end

  resources :levels

  resources :swords

  resources :kaitens

  resources :directions

  resources :techniques

  resources :maka_komis

  resources :hand_applied_tos

  resources :attack_heights

  resources :attacks

  resources :stances

  root 'wazas#only_on_test'

end

app/models/video.rb
#  http://img.youtube.com/vi/C5IWhAqQYfg/default.jpg
class Video < ActiveRecord::Base
  include Printable
  include SeedFuSerializeable

  after_save :set_keywords

  belongs_to :waza
  accepts_nested_attributes_for :waza

  delegate :stance, to: :waza, allow_nil: true
  delegate :entrance, to: :waza, allow_nil: true
  delegate :attack, to: :waza, allow_nil: true
  delegate :attack_height, to: :waza, allow_nil: true
  delegate :hand_applied_to, to: :waza, allow_nil: true
  delegate :maka_komi, to: :waza, allow_nil: true
  delegate :technique, to: :waza, allow_nil: true
  delegate :direction, to: :waza, allow_nil: true
  delegate :kaiten, to: :waza, allow_nil: true
  delegate :sword, to: :waza, allow_nil: true
  delegate :level, to: :waza, allow_nil: true
  delegate :csv_headers, to: :class

  belongs_to :aiki_format
  delegate :iaido?, to: :aiki_format, allow_nil: true

  belongs_to :kata
  belongs_to :rank
  belongs_to :sensei
  belongs_to :style

  scope :has_waza, -> { where(arel_table[:waza_id].not_eq(nil)) }
  scope :has_aiki_format, -> { where(arel_table[:aiki_format_id].not_eq(nil)) }
  scope :missing_waza, -> { where(waza: nil) }
  scope :missing_aiki_format, -> { where(aiki_format: nil) }
  scope :needs_review, -> { where( arel_table[:needs_review].eq(true).or(arel_table[:aiki_format_id].eq(nil).or(arel_table[:waza_id].eq(nil).or(arel_table[:youtube_id].eq(nil)))) ) }
  scope :by_waza_name, -> { joins(:waza).order("wazas.name") }
  scope :on_test, -> { where(on_test: true) }

  validates :aiki_format, presence: true
  validates :youtube_id, presence: true

  def self.search(keyword)
    results = []
    if keyword.present?
      results = where('keywords like ?', "%#{keyword.downcase}%")
      results = results.to_a
      if keyword.downcase == 'ikkyo'
        results.to_a.reject!{|r| r.keywords.include?('nikkyo') }
      end
    end
    results
  end

  def self.wazas(videos)
    videos.to_a unless videos.instance_of? Array
    videos.map(&:waza)
  end

  def self.to_csv
    [].tap do |rows|
      rows << csv_headers
      Video.all.each do |video|
        rows << video.to_csv
      end
    end
  end

  def self.csv_headers
    [
      "name",
      "format",
      "file_date",
      "class_date",
      "youtube",
      "waza_id",
      "video_id",
      "stance",
      "technique",
      "direction",
      "entrance",
      "attack",
      "attack_height",
      "hand_applied_to",
      "maka_komi",
      "kaiten",
      "sword",
      "level",
      "kata",
      "style",
      "sensei",
      "rank",
    ].join(",").freeze
  end

  def to_csv
    [
      name,
      format,
      nil,
      nil,
      youtube_id,
      waza_id,
      id,
      stance.try(:name),
      technique.try(:name),
      direction.try(:name),
      entrance.try(:name),
      attack.try(:name),
      attack_height.try(:name),
      hand_applied_to.try(:name),
      maka_komi.try(:name),
      kaiten.try(:name),
      sword.try(:name),
      level.try(:name),
      kata.try(:name),
      style.try(:name),
      sensei.try(:name),
      rank.try(:name),
    ].join(",").freeze
  end

  def update_video(video_params, waza_params={})
    return unless video_params && !video_params.empty?
    self.assign_attributes(video_params)
    unless waza_params.empty?
      waza = Waza.find_or_create_by(Waza.new(waza_params).to_h.except(:id, :name))
      self.waza = waza if waza
    end
    save
  end

  def name
    read_attribute(:name).present? ? read_attribute(:name) : waza.name rescue 'not set'
  end

  def format
    aiki_format.to_s rescue 'Other'
  end

  def inspect
    labels = [
      name,
      rank ? rank.name : 'Un-Ranked',
      format,
      needs_review? ? 'Needs Review' : nil
    ].compact.join(' / ')
    "<#{identify(:id, :waza_id, :youtube_id)} #{labels}"
  end

  def set_keywords
    waza_attribs = []

    if waza && waza.read_attribute(:name).present?
      waza_attribs = waza.name.split(" ").map(&:downcase)
    end

    single_attribs = [:stance,
                      :entrance,
                      :attack,
                      :attack_height,
                      :hand_applied_to,
                      :maka_komi,
                      :technique,
                      :direction,
                      :kaiten,
                      :sword,
                      :level,
                      :aiki_format,
                      :kata,
                      :rank,
                      :sensei,
                      :style]

    single_attribs.each do |attrib|
      waza_attribs << self.send(attrib, true).to_s.downcase
    end

    if kata
      waza_attribs << "iaido"
    else
      waza_attribs << "aikido"
    end

    waza_attribs << youtube_id if youtube_id

    waza_attribs << self.read_attribute(:name).downcase if self.read_attribute(:name).present?

    waza_attribs.reject!(&:blank?)
    waza_attribs.uniq!

    self.keywords = waza_attribs.join(' ').strip
    self.update_column(:keywords, keywords)
    keywords
  end
end

app/controllers/videos_controller.rb
class VideosController < AdminController
  before_action :signed_in_user
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.has_waza.by_waza_name.page(params[:page])
    @count = Video.has_waza.count
  end

  def needs_review
    if params[:search].present?
      @search = params[:search]
      @videos = Video.search(@search)
    else
      @videos = Video.needs_review.page(params[:page])
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
    @video.aiki_format = AikiFormat.find_by(name: "Tiado") rescue nil
    @video.sensei = Sensei.find_by(name: "John Bollinger") rescue nil
    @video.style = Style.find_by(name: "Tachi Waza") rescue nil
    @include_waza_form = false
  end

  # GET /videos/1/edit
  def edit
    @include_waza_form = true
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update_video(video_params, waza_params)
        format.html {
          if params["display"] && params["display"] == 'waza_display'
            redirect_to waza_display_path(waza_id: @video.waza.id, video_id: @video.id), notice: 'Video was successfully updated.'
          else
            redirect_to @video, notice: 'Video was successfully updated.'
          end
        }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  private

    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:name,
                                    :waza_id,
                                    :aiki_format_id,
                                    :kata_id,
                                    :sensei_id,
                                    :style_id,
                                    :rank_id,
                                    :on_test,
                                    :needs_review,
                                    :primary,
                                    :public,
                                    :youtube_id).reject!{|k,v| k != "name" && v.blank?}
    end

    def waza_params
      params.require(:waza).permit(:stance_id,
                                   :entrance_id,
                                   :attack_id,
                                   :attack_height_id,
                                   :hand_applied_to_id,
                                   :maka_komi_id,
                                   :technique_id,
                                   :direction_id,
                                   :kaiten_id,
                                   :sword_id,
                                   :level_id).reject!{|_,v| v.blank?}
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |vid_form| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% display ||= 'video_display' %>
  <%= hidden_field_tag 'display', display %>

  <div class="row pad_top_bottom">
    <div class="col-md-2">
      <h2>Video</h2>
    </div>
    <div class="col-md-3"  style="padding-top: 25px;">
      <div class="field input_inline">
        <%= vid_form.label :needs_review %>
        <%= vid_form.check_box :needs_review %>
      </div>
    </div>
  </div>

  <div class="row pad_top_bottom">
    <div class="col-md-3">
      <div class="field">
        <%= vid_form.label :name %><br>
        <%= vid_form.text_field :name %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= vid_form.label :youtube_id %><br>
        <%= vid_form.text_field :youtube_id %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field input_inline">
        <%= vid_form.label :on_test %><br>
        <%= vid_form.check_box :on_test %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field input_inline">
        <%= vid_form.label :primary, "Primary for Waza:" %><br>
        <%= vid_form.check_box :primary %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field input_inline">
        <%= vid_form.label :public, "Visible to Public:" %><br>
        <%= vid_form.check_box :public %>
      </div>
    </div>
  </div>

  <div class="row pad_top_bottom">
    <div class="col-md-2">
      <div class="field">
        <%= vid_form.label :aiki_format_id, "Format" %><br>
        <%= vid_form.select :aiki_format_id, options_for_select(AikiFormat.all.collect { |k| [ k.name, k.id ] }, @video.aiki_format_id), { include_blank: true } %>
      </div>
    </div>

    <div class="col-md-2">
      <div class="field">
        <%= vid_form.label :kata_id, "Kata" %><br>
        <%= vid_form.select :kata_id, options_for_select(Kata.all.collect { |k| [ k.name, k.id ] }, @video.kata_id), { include_blank: true } %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="field">
        <%= vid_form.label :style_id %><br>
        <%= vid_form.select :style_id, options_for_select(Style.all.collect { |k| [ k.name, k.id ] }, @video.style_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= vid_form.label :sensei_id %><br>
        <%= vid_form.select :sensei_id, options_for_select(Sensei.all.collect { |k| [ k.name, k.id ] }, @video.sensei_id), { include_blank: true } %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= vid_form.label :rank_id %><br>
        <%= vid_form.select :rank_id, options_for_select(Rank.all.collect { |k| [ k.name, k.id ] }, @video.rank_id), { include_blank: true } %>
      </div>
    </div>
  </div>

  <%
    if @include_waza_form && can?(:update, :waza)
      waza = @video.waza ||= @video.build_waza
  %>
    <%= render 'videos/video_waza', waza: waza %>
  <% end %>

  <div class="actions">
    <%= vid_form.submit %>
  </div>
<% end %>

app/views/videos/_list.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th colspan="2">Name</th>
      <th>Primary</th>
      <th>Waza</th>
      <th>Aiki format</th>
      <th>Rank</th>
      <th>On test</th>
      <th>Youtube</th>
      <% if current_user && can?(:update, :video) %>
        <th>Needs Review</th>
      <% end %>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% videos.each do |video| %>
      <tr>
        <td><%= video.id %></td>
        <td><%= link_to video.name, video %></td>
        <td><%= link_to image_tag("http://img.youtube.com/vi/#{video.youtube_id}/default.jpg", size: "120x90"),
                waza_display_path(waza_id: video.waza.id, video_id: video.id) %></td>
        <td><%= video.primary? ? 'Primary' : '' %></td>
        <td><%= link_to video.waza, waza_path(video.waza) %></td>
        <%
          format = video.aiki_format.to_s
          if format == 'Aiki Toho'
            format += " (#{video.kata})"
          end
        %>
        <td><%= format %></td>
        <td><%= video.rank %></td>
        <td><%= video.on_test %></td>
        <td><%= link_to video.youtube_id, "https://www.youtube.com/watch?v=#{video.youtube_id}" %></td>
        <% if current_user && can?(:update, :video) %>
          <td><%= video.needs_review? ? 'Needs Review' : '' %></td>
        <% end %>
        <td><%= link_to 'Watch', waza_display_path(video.waza, video_id: video) %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/videos/_video_waza.html.erb
<div id="waza_form">
  <%= fields_for :waza, waza do |waza_form| %>
    <%= render 'wazas/form', waza_form: waza_form, hide_name: true %>
  <% end %>
</div>

app/views/videos/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render 'wazas/video', video: @video %>
  </div>
</div>
<% if can?(:update, :video) %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= render 'form' %>
    </div>
  </div>
<% end %>

<%= link_to @video.youtube_id, "https://www.youtube.com/watch?v=#{@video.youtube_id}" %> |
<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Videos (<%= @count %>)</h1>
<%= link_to 'New Video', new_video_path %>
<br/>
<br/>
<%= will_paginate @videos %>
  <%= render 'list', videos: @videos %>
<%= will_paginate @videos %>
<br/>
<%= link_to 'New Video', new_video_path %>

app/views/videos/needs_review.html.erb
<% @search ||= nil %>
<h1>Unassigned Videos<%= @search.present? ? '' : " (#{Video.needs_review.count})" %></h1>

<%= form_tag needs_review_videos_path, method: :get do %>
  <div class="row">
    <div class="col-md-4">
      <%= render 'wazas/search_form' %>
    </div>
  </div>
<% end %>

<% unless @search %>
  <%= will_paginate @videos %>
<% end %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th colspan="2">Name</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.id %></td>
        <td><%= video.name %></td>
        <td><%= image_tag("http://img.youtube.com/vi/#{video.youtube_id}/default.jpg",
                          class: "header_image",
                          size: "120x90",
                          style: "margin-top: -20px; margin-bottom: 20px") %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% unless @search %>
  <%= will_paginate @videos %>
<% end %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @video.name rescue 'n/a' %>
</p>

<% if @video.needs_review %>
<p>
  <strong>Needs Review</strong>
</p>
<% end %>

<p>
  <strong>Waza:</strong>
  <% if @video.waza %>
    <%= link_to @video.waza, @video.waza %>
  <% else %>
    'n/a'
  <% end %>
</p>

<% if @video.waza %>
<p>
  <strong>Video:</strong>
  <%= link_to image_tag("http://img.youtube.com/vi/#{@video.youtube_id}/default.jpg", size: "120x90"),
                waza_display_path(waza_id: @video.waza.id, video_id: @video.id) %>
</p>
<% end %>

<p>
  <strong>Aiki format:</strong>
  <%= @video.aiki_format rescue 'n/a' %>
</p>

<% if @video.aiki_format.to_s == 'Aiki Toho' %>
  <p>
    <strong>Kata:</strong>
    <%= @video.kata rescue 'n/a' %>
  </p>
<% end %>

<p>
  <strong>Sensei:</strong>
  <%= @video.sensei rescue 'n/a' %>
</p>

<p>
  <strong>Style:</strong>
  <%= @video.style rescue 'n/a' %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @video.rank rescue 'n/a' %>
</p>

<p>
  <strong>On test:</strong>
  <%= @video.on_test rescue 'n/a' %>
</p>

<p>
  <strong>Youtube:</strong>
  <%= @video.youtube_id rescue 'n/a' %>
</p>

<% if Rails.env.development? %>
<p>
  <strong>Keywords:</strong>
  <%= @video.keywords rescue 'n/a' %>
</p>
<% end %>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>

app/views/videos/unassigned.html.erb
<h1>Unassigned Videos</h1>
<%= will_paginate @videos %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th colspan="2">Name</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.id %></td>
        <td><%= video.name %></td>
        <td><%= image_tag("http://img.youtube.com/vi/#{video.youtube_id}/default.jpg", class: "header_image", size: "120x90") %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @videos %>