config/routes.rb
Aiki3::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :entrances

  resources :katas

  resources :styles

  resources :senseis

  resources :videos do
    get 'needs_review', on: :collection
  end

  resources :ranks

  resources :aiki_formats

  resources :wazas do
    get 'master_grid', on: :collection
    get 'show_master_grid', on: :collection
    get 'only_on_test', on: :collection
    get 'display'
    get 'remote_display'
    get 'remote_waza'
    get 'rows', on: :collection
  end

  resources :levels

  resources :swords

  resources :kaitens

  resources :directions

  resources :techniques

  resources :maka_komis

  resources :hand_applied_tos

  resources :attack_heights

  resources :attacks

  resources :stances

  root 'wazas#only_on_test'

end

app/models/aiki_format.rb
class AikiFormat < ActiveRecord::Base
  include Printable
  include Searchable
  include SeedFuSerializeable

  has_many :videos
  has_many :wazas, through: :videos

  def iaido?
    to_s == 'Aiki Toho'
  end
end

app/controllers/aiki_formats_controller.rb
class AikiFormatsController < AdminController
  before_action :set_aiki_format, only: [:show, :edit, :update, :destroy]

  # GET /aiki_formats
  # GET /aiki_formats.json
  def index
    @aiki_formats = AikiFormat.all
  end

  # GET /aiki_formats/1
  # GET /aiki_formats/1.json
  def show
  end

  # GET /aiki_formats/new
  def new
    @aiki_format = AikiFormat.new
  end

  # GET /aiki_formats/1/edit
  def edit
  end

  # POST /aiki_formats
  # POST /aiki_formats.json
  def create
    @aiki_format = AikiFormat.new(aiki_format_params)

    respond_to do |format|
      if @aiki_format.save
        format.html { redirect_to @aiki_format, notice: 'Format was successfully created.' }
        format.json { render action: 'show', status: :created, location: @aiki_format }
      else
        format.html { render action: 'new' }
        format.json { render json: @aiki_format.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aiki_formats/1
  # PATCH/PUT /aiki_formats/1.json
  def update
    respond_to do |format|
      if @aiki_format.update(aiki_format_params)
        format.html { redirect_to @aiki_format, notice: 'Format was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @aiki_format.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aiki_formats/1
  # DELETE /aiki_formats/1.json
  def destroy
    @aiki_format.destroy
    respond_to do |format|
      format.html { redirect_to aiki_formats_url }
      format.json { head :no_content }
    end
  end

  private
    
    def set_aiki_format
      @aiki_format = AikiFormat.find(params[:id])
    end

    def aiki_format_params
      params.require(:aiki_format).permit(:name, :description)
    end
end

app/helpers/aiki_formats_helper.rb
module AikiFormatsHelper
end

app/views/aiki_formats/_form.html.erb
<%= form_for(@aiki_format) do |f| %>
  <% if @aiki_format.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aiki_format.errors.count, "error") %> prohibited this aiki_format from being saved:</h2>

      <ul>
      <% @aiki_format.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit @aiki_format.new_record? ? 'Create Format' : 'Update Format' %>
  </div>
<% end %>

app/views/aiki_formats/edit.html.erb
<h1>Editing Format</h1>

<%= render 'form' %>

<%= link_to 'Show', @aiki_format %> |
<%= link_to 'Back', aiki_formats_path %>

app/views/aiki_formats/index.html.erb
<h1>Listing Formats</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aiki_formats.each do |aiki_format| %>
      <tr>
        <td><%= aiki_format.id %></td>
        <td><%= aiki_format.name %></td>
        <td><%= aiki_format.description %></td>
        <td><%= link_to 'Show', aiki_format %></td>
        <td><%= link_to 'Edit', edit_aiki_format_path(aiki_format) %></td>
        <td><%= link_to 'Destroy', aiki_format, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Format', new_aiki_format_path %>

app/views/aiki_formats/new.html.erb
<h1>New Format</h1>

<%= render 'form' %>

<%= link_to 'Back', aiki_formats_path %>

app/views/aiki_formats/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @aiki_format.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @aiki_format.description %>
</p>

<%= link_to 'Edit', edit_aiki_format_path(@aiki_format) %> |
<%= link_to 'Back', aiki_formats_path %>